spring:
  application:
    name: personal-table

#  h2:
#    console:
#      enabled: true
#      path: /h2_console
#
#  datasource:
#    url: jdbc:h2:file:~/personal_table_db
#    data-username: sa
#    password:
#    driver-class-name: org.h2.Driver

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      show-sql: true

server:
  port: 9102

security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: oauth2_id