security:
  basic:
    authorize-mode:
  oauth2:
    resource:
      id: oauth2_id
    client:
      scope: read, write
      auto-approve-scopes: '.*'
      clientId: acme
      clientSecret: acmesecret

server:
  port: 9103